version: '3.9'
services:
  influxdb:
    image: influxdb:1.8.10
    hostname: influxdb
    container_name: influxdb__centralgrafana
    restart: unless-stopped

    environment:
      # I TRUST THE CLOUDFLARE ACCESS!!! XD
      INFLUXDB_DB: gnknzm_db
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: password
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: password

    volumes:
      - type: volume
        source: influxdb_data
        target: /var/lib/influxdb

      - type: volume
        source: influxdb_config
        target: /etc/influxdb

    networks:
      - internal

    deploy:
      resources:
        limits:
          memory: 512m

  grafana:
    image: grafana/grafana:10.1.1
    hostname: grafana
    container_name: grafana__centralgrafana
    restart: unless-stopped

    environment:
      # I TRUST THE CLOUDFLARE ACCESS!!! XD
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_USERS_ALLOW_ORG_CREATE: "false"

    volumes:
      - type: volume
        source: grafana_data
        target: /var/lib/grafana

    networks:
      internal:
      outband:

    deploy:
      resources:
        limits:
          memory: 512m

  cloudflared:
    image: cloudflare/cloudflared:2023.8.2-arm64@sha256:e1770d32ee66b0f4fb264526a7a2bcca46120ee149b5c7d13ba1a11600ff51fb
    hostname: cloudflared
    container_name: cloudflared__centralgrafana
    restart: unless-stopped

    environment:
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}

    networks:
      internal:
      outband:

    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  influxdb_config:
    name: centralgrafana__influxdb_config

  influxdb_data:
    name: centralgrafana__influxdb_data

  grafana_data:
    name: centralgrafana__grafana_data

networks:
  internal:
    name: centralgrafana__internal
    internal: true

  outband:
    name: centralgrafana__outband
